version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout 
     
      - run:
          name: install npm dependecies
          command: |
            npm install --save
      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit
     
      - run:
          name: Run tests with JUnit as reporter
          command: npm test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/

workflows:
  build_test:
    jobs:
      - run_tests