version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  run_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: \
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      

workflows:
  build_test:
    jobs:
      - run_tests