version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout 
      - run:
          name: install npm dependecies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: npm test 
     

workflows:
  build_test:
    jobs:
      - run_tests