version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  run_tests:
    
    docker:
      - image: circleci/node:10
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - store_test_results:
         path: test-results
      - store_artifacts:
          path: test-results

workflows:
  build_test:
    jobs:
      - run_tests