version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout 
      - run:
          name: install npm dependecies
          command: |
            npm install --save
      - save_cache:
              key: npm-cache-v1-{{ checksum "package.json" }}
              paths:
                - node_modules
      - run:
          name: Run Unit Tests
          command: | 
            npm test 
      - store_test_results:
          path: test

workflows:
  build_test:
    jobs:
      - run_tests