version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
workflows:
  build_test:
    jobs:
      - run_tests