version: 2.1
orbs:
  node: circleci/node@5.0.2
 

jobs:
  build_and_test:
    docker:
    -circleci/node:16.15.0
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
 
workflows:
  test_my_app:
    jobs:
      - build_and_test
      