version: 2.1
orbs:
  win: circleci/windows@4.1
jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: install npm dependecies
          command: |
            npm install --save
workflows:
  my-workflow:
    jobs:
      - build