version: 2.1
orbs: 
  windows: circleci/windows@4.1.1
 

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout 
      - run:
          name: install npm dependecies
          command: |
            npm install --save
      - run:
          command: npm test
          name: Run tests
      - store_test_results:
          path: ./test
 
workflows:
  test_my_app:
    jobs:
      - build