version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout 
      - restore_cache:
              key: npm-cache-v1-{{ checksum "package.json" }}
      - run:
          name: install npm dependecies
          command: |
            npm install --save
      - save_cache:
              key: npm-cache-v1-{{ checksum "package.json" }}
              paths:
                - node_modules
      - run:
              name: Run Tests
              command: |
                mkdir -p ~/test-results/junit
                npm test --ci --reporters=mocha
      - store_test_results:
          path: ~/test-results

workflows:
  build_test:
    jobs:
      - run_tests